[[language]]
name = "sifr"
scope = "source.sifr"
file-types = ["sifr"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = ["sifr-lsp"]
auto-format = true

[language-server.sifr-lsp]
command = "sifr"
args = ["lsp", "--stdio"]
