name = "Sifr"
grammar = "sifr"
path_suffixes = ["sifr"]
line_comments = ["#"]
tab_size = 4
hard_tabs = false
language_servers = ["sifr"]
formatter = { language_server = { name = "sifr" } }
format_on_save = "on"
scope = "source.sifr"
